export const GAME_CONFIG = {
    gameFHDWidth: 2560,
    gameFHDHeight: 1440,
    gameHDWidth: 1920,
    gameHDHeight: 1080,
    desktopWidth: 1920,
    desktopHeight: 1080,
    gameBGColor: 0x000000,
    globalAnimSpeed: 0.50,
    debugMode: false,
    gameName: "Race to Riches",
    configPath: "gameassets/",
    commonPath: "../common/",
    gamePath: "gameassets/",
    gameVersion: "0.06",
    gameId: "racetoriches",
    noOfLines: 20,
    creditValue: 1,
    initURL: "init",
    spinURL: "spin",
    bonusURL: "feature",
    scatter: "FG",
    bigWinMultipliers: [0, 25, 50, 100],
    messageTimeoutDelay: 16000,
    winDestroyDelay: 0.5,
    playerId: "123441",
    playLineWinSound: true,
    isStandAlone: false,
    dontCountUp: false,
    rtpValue: "97.00",
    featureTypes: {
        megaboard: "megaboard",
        freespins: "freespins",
        bigMoneyMultiplier : "bigMoneyMultiplier"
    }
}
