export const BONUS_GAME_CONFIG = {
    name: "bonusComp", type: "Comp", class: "BonusView",
    resizeChildren: true,
    Elements: [
        {
            name: "bonusBg", type: "DualImage", image: "fsMegaboardbg",
            layoutData: {
                "Desktop": { hAlign: "center", vAlign: "middle", fitToScreen: true },
                "Portrait": { hAlign: "center", vAlign: "top", fitToScreen: true },
                "Landscape": { hAlign: "center", vAlign: "top", fitToScreen: true },
            }
        },
        {
            name: "bonusContainer", type: "Comp", class: "BonusGame",
            Elements: [
                { name: "guideRect", type: "Graphics", color: 0xff0000, width: 2560, height: 1455, pWidth: 1916, pHeight: 2016, lWidth: 2560, lHeight: 1455, alpha: 0 },
                { name: "raceTrack", type: "DualImage", image: "bonusGamebg", x: 0, y: 0, },
                {
                    name: "bonusContainerBottom", type: "Comp", class: "BonusGameBottom", x: 0, y: 0,
                    Elements: [
                        { name: "guideRect", type: "Graphics", color: 0xffff00, width: 2560, height: 1455, pWidth: 1916, pHeight: 2016, lWidth: 2560, lHeight: 1455, alpha: 0 },
                        {
                            name: "level3Elements", type: "Comp", class: "GameResizeComp", x: 0, y: 0,
                            Elements: [
                                { name: "5xBet_4", type: "Sprite", image: "5x-bet-small", x: 1450, y: 1050, scale: 0.7, id: 1 },
                                { name: "20WildAdded_3", type: "Sprite", image: "20x_wild", x: 1100, y: 1050, scale: 0.7, id: 2 },
                                { name: "20MysteryAdded_3", type: "Sprite", image: "20x_mystery", x: 730, y: 1040, scale: 0.7, id: 3 },
                                { name: "beerRemoved", type: "Sprite", image: "beer_Removed", x: 390, y: 1040, scale: 0.7, id: 4 },
                                { name: "10xBet_1", type: "Sprite", image: "10x-bet-small", x: 161, y: 892, scale: 0.6, id: 5 },
                                { name: "50MysteryAdded_1", type: "Sprite", image: "50x_mystery", x: 121, y: 618, scale: 0.55, id: 6 },
                                { name: "50WildAdded_1", type: "Sprite", image: "50x_wild", x: 179, y: 391, scale: 0.53, id: 7 },
                                { name: "5xBet_5", type: "Sprite", image: "5x-bet-small", x: 273, y: 166, scale: 0.5, id: 8 },
                                { name: "20MysteryAdded_4", type: "Sprite", image: "20x_mystery", x: 523, y: 42, scale: 0.5, id: 9 },
                                { name: "10xBet_2", type: "Sprite", image: "10x-bet-small", x: 830, y: 30, scale: 0.5, id: 10 },
                                { name: "allReelWinsx5", type: "Sprite", image: "all-reels-wins_X5", x: 1150, y: 32, scale: 0.5, id: 11 },
                                { name: "20WildAdded_4", type: "Sprite", image: "20x_wild", x: 1459, y: 32, scale: 0.5, id: 12 },
                                { name: "5xBet_6", type: "Sprite", image: "5x-bet-small", x: 1785, y: 57, scale: 0.5, id: 13 },
                                { name: "50MysteryAdded_2", type: "Sprite", image: "50x_mystery", x: 2007, y: 170, scale: 0.5, id: 14 },
                                { name: "10xBet_3", type: "Sprite", image: "10x-bet-small", x: 2111, y: 396, scale: 0.5, id: 15 },
                                { name: "capRemoved", type: "Sprite", image: "cap_Removed", x: 2133, y: 636, scale: 0.5, id: 16 },
                                { name: "50WildAdded_2", type: "Sprite", image: "50x_wild", x: 2113, y: 899, scale: 0.5, id: 17 },
                                { name: "bigWin", type: "Sprite", image: "bigmoney", x: 1830, y: 1050, scale: 0.6, id: 18 },
                            ]
                        },
                        {
                            name: "level2Elements", type: "Comp", class: "GameResizeComp", x: 0, y: 0,
                            Elements: [
                                { name: "2xBet_4", type: "Sprite", image: "2x-bet-small", x: 1450, y: 1050, scale: 0.7, id: 1 },
                                { name: "10WildAdded_3", type: "Sprite", image: "10x_wild", x: 1100, y: 1050, scale: 0.7, id: 2 },
                                { name: "10MysteryAdded_3", type: "Sprite", image: "10x_mystery", x: 730, y: 1040, scale: 0.7, id: 3 },
                                { name: "spadeRemoved", type: "Sprite", image: "spade_Removed", x: 390, y: 1040, scale: 0.7, id: 4 },
                                { name: "5xBet_1", type: "Sprite", image: "5x-bet-small", x: 161, y: 892, scale: 0.6, id: 5 },
                                { name: "20MysteryAdded_1", type: "Sprite", image: "20x_mystery", x: 121, y: 618, scale: 0.55, id: 6 },
                                { name: "20WildAdded_1", type: "Sprite", image: "20x_wild", x: 179, y: 391, scale: 0.53, id: 7 },
                                { name: "2xBet_5", type: "Sprite", image: "2x-bet-small", x: 273, y: 166, scale: 0.5, id: 8 },
                                { name: "10MysteryAdded_4", type: "Sprite", image: "10x_mystery", x: 523, y: 42, scale: 0.5, id: 9 },
                                { name: "5xBet_2", type: "Sprite", image: "5x-bet-small", x: 830, y: 30, scale: 0.5, id: 10 },
                                { name: "allReelWinsx3", type: "Sprite", image: "all-reels-wins_X3", x: 1150, y: 32, scale: 0.5, id: 11 },
                                { name: "10WildAdded_4", type: "Sprite", image: "10x_wild", x: 1459, y: 32, scale: 0.5, id: 12 },
                                { name: "2xBet_6", type: "Sprite", image: "2x-bet-small", x: 1785, y: 57, scale: 0.5, id: 13 },
                                { name: "20MysteryAdded_2", type: "Sprite", image: "20x_mystery", x: 2007, y: 170, scale: 0.5, id: 14 },
                                { name: "5xBet_3", type: "Sprite", image: "5x-bet-small", x: 2111, y: 396, scale: 0.5, id: 15 },
                                { name: "heartRemoved", type: "Sprite", image: "heart_Removed", x: 2133, y: 636, scale: 0.5, id: 16 },
                                { name: "20WildAdded_2", type: "Sprite", image: "20x_wild", x: 2113, y: 899, scale: 0.5, id: 17 },
                                { name: "winSpin_2", type: "Sprite", image: "winspin", x: 1830, y: 1050, scale: 0.6, id: 18 },
                            ]
                        },
                        {
                            name: "level1Elements", type: "Comp", class: "GameResizeComp", x: 0, y: 0,
                            Elements: [
                                { name: "1xBet_1", type: "Sprite", image: "1x-bet-small", x: 1450, y: 1050, scale: 0.7, id: 1 },
                                { name: "5WildAdded_1", type: "Sprite", image: "5x_wild", x: 1100, y: 1050, scale: 0.7, id: 2 },
                                { name: "5MysteryAdded_1", type: "Sprite", image: "5x_mystery", x: 730, y: 1040, scale: 0.7, id: 3 },
                                { name: "clubRemoved", type: "Sprite", image: "clubs_Removed", x: 390, y: 1040, scale: 0.7, id: 4 },
                                { name: "2xBet_1", type: "Sprite", image: "2x-bet-small", x: 161, y: 892, scale: 0.6, id: 5 },
                                { name: "10MysteryAdded_1", type: "Sprite", image: "10x_mystery", x: 121, y: 618, scale: 0.55, id: 6 },
                                { name: "10WildAdded_1", type: "Sprite", image: "10x_wild", x: 179, y: 391, scale: 0.53, id: 7 },
                                { name: "1xBet_2", type: "Sprite", image: "1x-bet-small", x: 273, y: 166, scale: 0.5, id: 8 },
                                { name: "5MysteryAdded_2", type: "Sprite", image: "5x_mystery", x: 523, y: 42, scale: 0.5, id: 9 },
                                { name: "2xBet_2", type: "Sprite", image: "2x-bet-small", x: 830, y: 30, scale: 0.5, id: 10 },
                                { name: "allReelWinsx2", type: "Sprite", image: "all-reels-wins_X2", x: 1150, y: 32, scale: 0.5, id: 11 },
                                { name: "5WildAdded_2", type: "Sprite", image: "5x_wild", x: 1459, y: 32, scale: 0.5, id: 12 },
                                { name: "1xBet_3", type: "Sprite", image: "1x-bet-small", x: 1785, y: 57, scale: 0.5, id: 13 },
                                { name: "10MysteryAdded_2", type: "Sprite", image: "10x_mystery", x: 2007, y: 170, scale: 0.5, id: 14 },
                                { name: "2xBet_3", type: "Sprite", image: "2x-bet-small", x: 2111, y: 396, scale: 0.5, id: 15 },
                                { name: "daimondRemoved", type: "Sprite", image: "daimond_Removed", x: 2133, y: 636, scale: 0.5, id: 16 },
                                { name: "10WildAdded_2", type: "Sprite", image: "10x_wild", x: 2113, y: 899, scale: 0.5, id: 17 },
                                { name: "winSpin_1", type: "Sprite", image: "winspin", x: 1830, y: 1050, scale: 0.6, id: 18 },
                            ]
                        },
                        { name: "greenParticleAnimation", type: "AnimatedSprite", animation: { prefix: "green_particular_000", postfix: "", start: 0, end: 59, toAddZero: true } },
                        {
                            name: "lapLevel", type: "Container", x: 2300, y: 1230, px: 1650, py: 1800, lx: 2300, ly: 1230,
                            Elements: [
                                { name: "lapBg", type: "Sprite", image: "lapBg" },
                                { name: "lapText", type: "Text", content: "lapText", style: "PopupMessage1Style", fontSize: 50, fontColor: ["0xfef47c", "0xd09300", "0xffdb0e", "0xfffc78", "0xffffee", "0xfbff6d", "0xffb519", "0xffdf5c"], stroke: "0x622a00", strokeThickness: 4, anchor: { x: 0.5, y: 0.5 }, x: 125, y: 73 },
                                { name: "lapLevel1", type: "Sprite", image: "lapLevel1Small", x: 51, y: 90 },
                                { name: "lapLevel2", type: "Sprite", image: "lapLevel2Small", x: 55, y: 90 },
                                { name: "lapLevel3", type: "Sprite", image: "lapLevel3Small", x: 53, y: 90 },
                            ],
                        },
                        {
                            name: "totalWinAmountComp", type: "Comp", class: "WinAmountComp", anchor: { x: 0.5, y: 0.5 }, x: 20, y: 1170, scale: 0.39,
                            Elements: [
                                { name: "winbg", type: "Sprite", image: "TotalWinBg", scale: { x: 1.3, y: 1 } },
                                { name: "winTitle", type: "Text", style: "PopupMessage4Style", content: "totalWinText", x: 475, y: 230, anchor: { x: 0.5, y: 0.5 }, fontSize: 150, fontColor: ["0x58d3fe", "0x266cfc", "0x205cf7", "0x1237ea", "0x0b23e3", "0x0615de", "0x040fdc"], stroke: "0x60605f", strokeThickness: 4 },
                                { name: "winText", type: "Text", style: "winAmountStyle1", contentText: 100.00, fontSize: 160, anchor: { x: 0.5, y: 0.5 }, x: 475, y: 500 }
                            ],
                        },
                    ],
                },
                {
                    name: "bonusContainerTop", type: "Comp", class: "BonusGameTop", x: 0, y: 0,
                    Elements: [
                        { name: "maskRect", type: "Graphics", color: 0xffff00, width: 600, height: 400, pWidth: 380, pHeight: 250, lWidth: 600, lHeight: 400, x: 985, y: 600, px: 660, py: 900, lx: 985, ly: 600, alpha: 0 },
                        {
                            name: "miniPopUp", type: "Container", x: 1031, y: 641, scale: 0.7,
                            Elements: [
                                { name: "popBg", type: "Sprite", image: "bonus_lap_popup" },
                                { name: "miniLapText1", type: "Text", contentText: "", style: "PopupMessage1Style", fontSize: 100, fontColor: ["0xc3e1ff", '0xbcdeff', "0xc2e0ff", "0xdaeaff", "0xacd0ff", "0x8fb5ff", "0x8bb0ff", "0x8bb0ff"], stroke: "0x2c2b48", strokeThickness: 4, anchor: { x: 0.5, y: 0.5 }, dropShadow: true, dropShadowColor: "0x1d573d", dropShadowDistance: 4, dropShadowAlpha: 0.4, x: 366, y: 130 },
                                { name: "miniLapLevel1", type: "Sprite", image: "lapLevel1Big", x: 187, y: 220 },
                                { name: "miniLapText2", type: "Text", contentText: "", style: "PopupMessage1Style", fontSize: 100, fontColor: ["0x9afbac", "0x439864", "0x83f897", "0x99fdad", "0xa3ffb6", "0xa3ffb6", "0x37c852", "0x24c345", "0x067634"], stroke: "0x2d2d2d", strokeThickness: 4, anchor: { x: 0.5, y: 0.5 }, dropShadow: true, dropShadowColor: "0x025401", dropShadowDistance: 4, dropShadowAlpha: 0.4, x: 366, y: 130 },
                                { name: "miniLapLevel2", type: "Sprite", image: "lapLevel2Big", x: 187, y: 220 },
                                { name: "miniLapText3", type: "Text", contentText: "", style: "PopupMessage1Style", fontSize: 100, fontColor: ["0xfef47c", "0xd09300", "0xffdb0e", "0xfffc78", "0xffffee", "0xfbff6d", "0xffb519", "0xffdf5c"], stroke: "0x622a00", strokeThickness: 4, anchor: { x: 0.5, y: 0.5 }, dropShadow: true, dropShadowColor: "0x1d573d", dropShadowDistance: 4, dropShadowAlpha: 0.4, x: 366, y: 130 },
                                { name: "miniLapLevel3", type: "Sprite", image: "lapLevel3Big", x: 187, y: 220 }
                            ]
                        },
                        { name: "extraRollText", type: "Text", style: "PopupMessage5Style", fontSize: 120, pFontSize: 60, fontColor: ["0xff6270", "0xff1806", "0xe91409", "0xc40e0d", "0x9e0711", "0x890414"], stroke: "0x3eff9c", strokeThickness: 12, anchor: { x: 0.5, y: 0.5 }, dropShadow: true, dropShadowColor: "0x02714b", dropShadowDistance: 2, dropShadowAlpha: 0.4, x: 1290, y: 650 },
                        { name: "megaboardUpgradedText", type: "Text", style: "PopupMessage5Style", fontSize: 100, pFontSize: 60, fontColor: ["0xff6270", "0xff1806", "0xe91409", "0xc40e0d", "0x9e0711", "0x890414"], stroke: "0x3eff9c", strokeThickness: 12, anchor: { x: 0.5, y: 0.5 }, dropShadow: true, dropShadowColor: "0x02714b", dropShadowDistance: 2, dropShadowAlpha: 0.4, x: 1285, y: 450 },
                        {
                            name: "diceRotatingComp", type: "Comp", class: "DiceRotatingComp", x: 0, y: 0,
                            Elements: [
                                { name: "boyFace", type: "Sprite", image: "redMan", x: 1350, y: 820, scale: 0.7 },
                                { name: "monopolyManFace", type: "Sprite", image: "greenMan", x: 1020, y: 820, scale: 0.7 },
                                {
                                    name: "yellowDiceContainer", type: "Container", x: 1290, y: 830, visible: false,
                                    Elements: [
                                        { name: "yellowDiceAnim1", type: "AnimatedSprite", animation: { prefix: "g_1_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "yellowDiceLightAnim1", type: "AnimatedSprite", animation: { prefix: "1_yellow_light_anim_0000", postfix: "", start: 0, end: 6, toAddZero: false }, x: -2, y: 125 },
                                        { name: "yellowDiceAnim2", type: "AnimatedSprite", animation: { prefix: "g_2_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "yellowDiceLightAnim2", type: "AnimatedSprite", animation: { prefix: "2_yellow_light_anim_000", postfix: "", start: 0, end: 21, toAddZero: true }, x: -2, y: 125 },
                                        { name: "yellowDiceAnim3", type: "AnimatedSprite", animation: { prefix: "g_3_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "yellowDiceLightAnim3", type: "AnimatedSprite", animation: { prefix: "3_yellow_light_anim_000", postfix: "", start: 0, end: 36, toAddZero: true }, x: -2, y: 125 },
                                        { name: "yellowDiceAnim4", type: "AnimatedSprite", animation: { prefix: "g_4_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "yellowDiceLightAnim4", type: "AnimatedSprite", animation: { prefix: "4_yellow_light_anim_000", postfix: "", start: 0, end: 51, toAddZero: true }, x: -2, y: 125 },
                                        { name: "yellowDiceAnim5", type: "AnimatedSprite", animation: { prefix: "g_5_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "yellowDiceLightAnim5", type: "AnimatedSprite", animation: { prefix: "5_yellow_light_anim_000", postfix: "", start: 0, end: 66, toAddZero: true }, x: -2, y: 125 },
                                        { name: "yellowDiceAnim6", type: "AnimatedSprite", animation: { prefix: "g_6_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "yellowDiceLightAnim6", type: "AnimatedSprite", animation: { prefix: "6_yellow_light_anim_000", postfix: "", start: 0, end: 80, toAddZero: true }, x: -2, y: 125 },
                                    ]
                                },
                                {
                                    name: "purpleDiceContainer", type: "Container", x: 1290, y: 830, visible: false,
                                    Elements: [
                                        { name: "purpleDiceAnim1", type: "AnimatedSprite", animation: { prefix: "p_1_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "purpleDiceLightAnim1", type: "AnimatedSprite", animation: { prefix: "1_purple_light_anim_0000", postfix: "", start: 0, end: 6, toAddZero: false }, y: 124 },
                                        { name: "purpleDiceAnim2", type: "AnimatedSprite", animation: { prefix: "p_2_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "purpleDiceLightAnim2", type: "AnimatedSprite", animation: { prefix: "2_purple_light_anim_000", postfix: "", start: 0, end: 21, toAddZero: true }, y: 124 },
                                        { name: "purpleDiceAnim3", type: "AnimatedSprite", animation: { prefix: "p_3_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "purpleDiceLightAnim3", type: "AnimatedSprite", animation: { prefix: "3_purple_light_anim_000", postfix: "", start: 0, end: 36, toAddZero: true }, y: 124 },
                                        { name: "purpleDiceAnim4", type: "AnimatedSprite", animation: { prefix: "p_4_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "purpleDiceLightAnim4", type: "AnimatedSprite", animation: { prefix: "4_purple_light_anim_000", postfix: "", start: 0, end: 51, toAddZero: true }, y: 124 },
                                        { name: "purpleDiceAnim5", type: "AnimatedSprite", animation: { prefix: "p_5_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "purpleDiceLightAnim5", type: "AnimatedSprite", animation: { prefix: "5_purple_light_anim_000", postfix: "", start: 0, end: 66, toAddZero: true }, y: 124 },
                                        { name: "purpleDiceAnim6", type: "AnimatedSprite", animation: { prefix: "p_6_000", postfix: "", start: 0, end: 36, toAddZero: true } },
                                        { name: "purpleDiceLightAnim6", type: "AnimatedSprite", animation: { prefix: "6_purple_light_anim_000", postfix: "", start: 0, end: 80, toAddZero: true }, y: 124 },
                                    ]
                                },
                                { name: "press2Roll", type: "Sprite", image: "press2roll", x: 1170, y: 900, scale: 0.7 },
                                { name: "press2RollBtn", type: "Graphics", color: 0x000000, width: 225, height: 145, x: 1180, y: 910 }
                            ]
                        },
                        { name: "bigWinTriggeredAnim", type: "Spine", spineName: "big_money", defaultSkin: "default", defaultState: "bm_idle", loop: true, scale: 1, x: 1280, y: 650 },
                        {
                            name: "monopolyContainer", type: "Container", scale: 0.6, x: 0, y: 0,
                            Elements: [
                                { name: "manInCar", type: "Spine", spineName: "manincar", defaultSkin: "default", defaultState: "car", loop: true, x: 3250, y: 1800 },
                                { name: "boyOnDuck", type: "Spine", spineName: "boyduck", defaultSkin: "default", defaultState: "animation", loop: true, x: 3380, y: 1980 },
                            ],
                        },
                        {
                            name: "levelHighlightElements", type: "Comp", class: "HighlightElementsComp", x: 495, y: 357, scale: 1,
                            Elements: [
                                { name: "guideRect", type: "Graphics", width: 1520, height: 600, x: 0, y: 0, color: 0xffffff, alpha: 0 },
                                { name: "removedBoxbg", type: "Sprite", image: "removedBoxBg", anchor: { x: 0.5, y: 0.5 }, x: 1440, y: 380, scale: 0.8 },
                                { name: "clubs", type: "Sprite", image: "Clubs", anchor: { x: 0.5, y: 0.5 }, scale: 0.3, x: 1440, y: 380 },
                                { name: "allReelWins2", type: "Sprite", image: "all-reels-wins_X2", anchor: { x: 0.5, y: 0.5 }, scale: 0.6, x: 100, y: 380 },
                                { name: "daimond", type: "Sprite", image: "Diamonds", anchor: { x: 0.5, y: 0.5 }, scale: 0.3, x: 1440, y: 380 },
                                { name: "spade", type: "Sprite", image: "Spades", anchor: { x: 0.5, y: 0.5 }, scale: 0.3, x: 1440, y: 380 },
                                { name: "allReelWins3", type: "Sprite", image: "all-reels-wins_X3", anchor: { x: 0.5, y: 0.5 }, scale: 0.6, x: 100, y: 380 },
                                { name: "heart", type: "Sprite", image: "Heart", anchor: { x: 0.5, y: 0.5 }, scale: 0.3, x: 1440, y: 380 },
                                { name: "beer", type: "Sprite", image: "Beer", anchor: { x: 0.5, y: 0.5 }, scale: 0.3, x: 1440, y: 380 },
                                { name: "allReelWins5", type: "Sprite", image: "all-reels-wins_X5", anchor: { x: 0.5, y: 0.5 }, scale: 0.6, x: 100, y: 380 },
                                { name: "cap", type: "Sprite", image: "Cap", anchor: { x: 0.5, y: 0.5 }, scale: 0.3, x: 1440, y: 380 },
                            ],
                            data: {
                                //level1
                                1: { name: "1x bet", type: "Sprite", image: "1x-bet" },
                                2: { name: "5WildAdded", type: "Sprite", image: "5x_wild" },
                                3: { name: "5MysteryAdded", type: "Sprite", image: "5x_mystery" },
                                4: { name: "clubsRemoved", type: "Sprite", image: "clubs_Removed" },
                                5: { name: "2x bet", type: "Sprite", image: "2x-bet" },
                                6: { name: "10MysteryAdded", type: "Sprite", image: "10x_mystery" },
                                7: { name: "10WildAdded", type: "Sprite", image: "10x_wild" },
                                8: { name: "1x bet", type: "Sprite", image: "1x-bet" },
                                9: { name: "5MysteryAdded", type: "Sprite", image: "5x_mystery" },
                                10: { name: "2x bet", type: "Sprite", image: "2x-bet" },
                                11: { name: "all reels wins X2", type: "Sprite", image: "all-reels-wins_X2" },
                                12: { name: "5WildAdded", type: "Sprite", image: "5x_wild" },
                                13: { name: "1x bet", type: "Sprite", image: "1x-bet" },
                                14: { name: "10MysteryAdded", type: "Sprite", image: "10x_mystery" },
                                15: { name: "2x bet", type: "Sprite", image: "2x-bet" },
                                16: { name: "daimondRemoved", type: "Sprite", image: "daimond_Removed" },
                                17: { name: "10WildAdded", type: "Sprite", image: "10x_wild" },
                                18: { name: "win-spin", type: "Sprite", image: "winspin" },
                                //level2
                                19: { name: "2xBet", type: "Sprite", image: "2x-bet" },
                                20: { name: "10WildAdded", type: "Sprite", image: "10x_wild" },
                                21: { name: "10MysteryAdded", type: "Sprite", image: "10x_mystery" },
                                22: { name: "spadeRemoved", type: "Sprite", image: "spade_Removed" },
                                23: { name: "5xBet", type: "Sprite", image: "5x-bet" },
                                24: { name: "20MysteryAdded", type: "Sprite", image: "20x_mystery" },
                                25: { name: "20WildAdded", type: "Sprite", image: "20x_wild" },
                                26: { name: "2xBet", type: "Sprite", image: "2x-bet" },
                                27: { name: "10MysteryAdded", type: "Sprite", image: "10x_mystery" },
                                28: { name: "5xBet", type: "Sprite", image: "5x-bet" },
                                29: { name: "allReelWinsx3", type: "Sprite", image: "all-reels-wins_X3" },
                                30: { name: "10WildAdded", type: "Sprite", image: "10x_wild" },
                                31: { name: "2xBet", type: "Sprite", image: "2x-bet" },
                                32: { name: "20MysteryAdded", type: "Sprite", image: "20x_mystery" },
                                33: { name: "5xBet", type: "Sprite", image: "5x-bet" },
                                34: { name: "heartRemoved", type: "Sprite", image: "heart_Removed" },
                                35: { name: "20WildAdded", type: "Sprite", image: "20x_wild" },
                                36: { name: "winSpin", type: "Sprite", image: "winspin" },
                                //level3
                                37: { name: "5xBet", type: "Sprite", image: "5x-bet" },
                                38: { name: "20WildAdded", type: "Sprite", image: "20x_wild" },
                                39: { name: "20MysteryAdded", type: "Sprite", image: "20x_mystery" },
                                40: { name: "beerRemoved", type: "Sprite", image: "beer_Removed" },
                                41: { name: "10xBet", type: "Sprite", image: "10x-bet" },
                                42: { name: "50MysteryAdded", type: "Sprite", image: "50x_mystery" },
                                43: { name: "50WildAdded", type: "Sprite", image: "50x_wild" },
                                44: { name: "5xBet", type: "Sprite", image: "5x-bet" },
                                45: { name: "20MysteryAdded", type: "Sprite", image: "20x_mystery" },
                                46: { name: "10xBet", type: "Sprite", image: "10x-bet" },
                                47: { name: "allReelWinsx5", type: "Sprite", image: "all-reels-wins_X5" },
                                48: { name: "20WildAdded", type: "Sprite", image: "20x_wild" },
                                49: { name: "5xBet", type: "Sprite", image: "5x-bet" },
                                50: { name: "50MysteryAdded", type: "Sprite", image: "50x_mystery" },
                                51: { name: "10xBet", type: "Sprite", image: "10x-bet" },
                                52: { name: "capRemoved", type: "Sprite", image: "cap_Removed" },
                                53: { name: "50WildAdded", type: "Sprite", image: "50x_wild" },
                                54: { name: "bigWin", type: "Sprite", image: "bigmoney" },
                            },
                        },
                    ],
                },
            ],
            layoutData: {
                "Desktop": { hAlign: "center", vAlign: "middle", widthPerc: 0.99, heightPerc: 0.99 },
                "Portrait": { hAlign: "center", vAlign: "top", vPaddingPerc: 0.1, widthPerc: 1 },
                "Landscape": { hAlign: "center", vAlign: "middle", heightPerc: 0.99 },
            }
        },
    ],

}
