export const GAME_CONFIG = {
    gameFHDWidth : 2560,
    gameFHDHeight : 1440,
    gameHDWidth : 1920,
    gameHDHeight : 1080,
    desktopWidth : 1920,
    desktopHeight : 1080,
    gameBGColor : 0x000000,
    globalAnimSpeed : 0.50,
    debugMode : false,
    gameName : "Three Dragons",
    configPath : "gameassets/",
    commonPath : "../common/",
    gamePath : "gameassets/",
    gameVersion : "0.06",
    gameId : "threedragons",
    noOfLines : 1,
    creditValue : 1,
    isFiveOfAKindWin : false,
    initURL : "init",
    spinURL : "spin",
    bonusURL : "feature",
    bigWinMultipliers : [0,5],
    payaoutMap: [5, 25,50,100],
    messageTimeoutDelay : 16000,
    winDestroyDelay : 0.5,
    playerId : "123441",
    playLineWinSound : true,
    showPaylinAnim : true,
    isStandAlone : false,
    rtpValue : "97.00",
    featureTypes : {
        bonusGame : "bonusGame",
        freespins : "freespins",
        cashaward : "cashaward"
    }
}
